//Its a start

const Event = require("../server/models/Event");
const mongoose = require ("mongoose");
//const dev = require ("../client/vite.config")

const Events = [
    new Event({
        name: "Yoga in the park",
        description: "Outdoor yoga session for all levels of practitioners, surrounded by nature.",
        Date: "September 30, 2023",
        beginTime: "9:00AM",
        endTime: "10:30AM",
        location: "Butterfly Park, 5200 Wornall Rd, Kansas City, MO",
        //image: "",
        type: "Sports",
        createdAt: new Date().tolSOString(),
        updatedAt: new Date().tolSOString(),
    }),
    new Event({
        name: "Classic Car Show",
        description: "A gathering of vintage automobiles showcasing their unique designs and historical significance.",
        Date: "September 15, 2023",
        beginTime: "10:00 AM",
        endTime: "4:00 PM",
        location: "2 Memorial Dr, Kansas City, MO",
        //image: "",
        type: "Automotive",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "Basketball Tournament",
        description: "A competitive basketball tournament featuring teams from the local community",
        Date: "November 20, 2023",
        beginTime: "9:00 AM",
        endTime: "6:00 PM",
        location: "11820 N Rose Dr, Kansas City, MO",
        //image: "",
        type: "Sports",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "Movie Night in the Park",
        description: " An outdoor screening of a family-friendly movie under the stars.",
        Date: "December 5, 2023",
        beginTime: "7:30 PM",
        endTime: "10:00 PM",
        location: "4600 Oak St, Kansas City, MO",
        //image: "",
        type: "Entertainment",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "Science Fair",
        description: "A showcase of innovative and educational science projects created by students.",
        Date: "November 10, 2023",
        beginTime: "9:00 AM",
        endTime: "3:00 PM",
        location: "Union Station Kansas City, 30 W Pershing Rd, Kansas City, MO",
        //image: "",
        type: "Educational",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "Pet Adoption Day",
        description: "An event where local animal shelters bring adorable pets available for adoption.",
        Date: "December 12, 2023",
        beginTime: "11:00 AM",
        endTime: "3:00 PM",
        location: "7077 Elmwood Ave, Kansas City, MO",
        //image: "",
        type: "Pets",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "Live Concert: Jazz Under the Stars",
        description: "A night of live jazz music featuring local musicians in an open-air setting.",
        Date: "September 12, 2023",
        beginTime: "7:00 PM",
        endTime: "11:00 PM",
        location: "Almond Park, 1 E 47th St, Kansas City, MO",
        //image: "",
        type: "Entertainment",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "Coding Workshop for Kids",
        description: "An educational workshop teaching coding basics to children.",
        Date: "November 5, 2023",
        beginTime: "2:00 PM",
        endTime: "4:00 PM",
        location: "4801 Main St, Kansas City, MO",
        //image: "",
        type: "Educational",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),
    new Event({
        name: "",
        description: "",
        Date: "",
        beginTime: "",
        endTime: "",
        location: "",
        //image: "",
        type: "",
        createdAt:new Date().tolSOString(),
        updatedAt:new Date().tolSOString(),
    }),



]

